"""LLM access layer: providers, a failover router, and usage accounting."""

from .base import (
    AllProvidersFailed,
    BadRequest,
    LLMError,
    LLMRequest,
    LLMResponse,
    Message,
    Provider,
    ProviderNotConfigured,
    ProviderUnavailable,
    RateLimited,
    Usage,
    assistant,
    system,
    user,
)
from .catalog import (
    GOOGLE,
    GROQ,
    OPENROUTER,
    PROVIDER_TEMPLATES,
    default_provider_configs,
    discover_openrouter_free_models,
)
from .providers import (
    EchoProvider,
    GoogleProvider,
    GroqProvider,
    OpenAICompatibleProvider,
    OpenRouterProvider,
    build_provider,
)
from .router import (
    CircuitBreaker,
    LLMRouter,
    RateLimiter,
    UsageRecord,
    UsageTracker,
    extract_json,
)

__all__ = [
    "AllProvidersFailed",
    "BadRequest",
    "CircuitBreaker",
    "EchoProvider",
    "GOOGLE",
    "GROQ",
    "GoogleProvider",
    "GroqProvider",
    "LLMError",
    "LLMRequest",
    "LLMResponse",
    "LLMRouter",
    "Message",
    "OPENROUTER",
    "OpenAICompatibleProvider",
    "OpenRouterProvider",
    "PROVIDER_TEMPLATES",
    "Provider",
    "ProviderNotConfigured",
    "ProviderUnavailable",
    "RateLimited",
    "RateLimiter",
    "Usage",
    "UsageRecord",
    "UsageTracker",
    "assistant",
    "build_provider",
    "default_provider_configs",
    "discover_openrouter_free_models",
    "extract_json",
    "system",
    "user",
]
